services:
  mysql-server:
    image: mysql:8.4
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password123!
      MYSQL_DATABASE: bprhire_DB
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bpr-backend
    restart: always
    ports:
      - "16940:16940"
    depends_on:
      - mysql-server
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bpr-frontend
    restart: always
    ports:
      - "80:80"
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql_data:
